{
 "title": "Monitor Pipeline",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run_dir",
    "query": "SELECT runs.run_dir || '\\' || runs.run_id from (\nSELECT run_id, max(unixtime) as maxunixtime\nFROM state_vector\nGROUP BY run_id\n) b join runs on runs.run_id = b.run_id\nwhere b.maxunixtime/1000000 > $__unixEpochFrom()\nORDER BY runs.run_dir ASC;"
   },
   {
    "name": "node_id",
    "query": "SELECT DISTINCT node_id\nFROM hosts\nWHERE run_id in (${run_dir:sqlstring})\nORDER BY node_id ASC;"
   },
   {
    "name": "bucket_interval",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "trigger_frequency",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "time_meaning", "label": "Timestamp Meaning", "query": "frame,finalsink" },
   { "name": "job", "label": "Job", "query": "node" },
   {
    "name": "node",
    "label": "Host: ",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MDC Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "MDC Injections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select\n  geocent_end_time + 315964782 + 101760000 as time,\n  coa_phase,\n  distance,\n  inclination,\n  latitude,\n  longitude,\n  mass1,\n  mass2,\n  mchirp,\n  phi0,\n  polarization,\n  spin1x,\n  spin1y,\n  spin1z,\n  spin2x,\n  spin2y,\n  spin2z\nfrom\n  sim_inspiral\nWHERE\n  $__unixEpochFilter(geocent_end_time + 315964782 + 101760000);"
      }
     ]
    }
   ]
  },
  {
   "title": "Host $node System Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$node:9100\",job=\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=\"$node:9100\",job=\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=\"$node:9100\",job=\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node:9100\",job=\"$job\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node:9100\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node:9100\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node:9100\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node:9100\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node:9100\",job=\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node:9100\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node:9100\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node:9100\",job=\"$job\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node:9100\",job=\"$job\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node:9100\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node:9100\",job=\"$job\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node:9100\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Per Process CPU",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\", instance=\"$node:9256\"}[30s])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Number of Processes",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\", instance=\"$node:9256\"}",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  { "title": "$run_dir", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "run_dir" },
  {
   "title": "Trigger latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH bucketed_hosts AS (\n  SELECT\n    host,\n    run_id,\n    node_id,\n    unixtime AS bucket_start,\n    LEAD(unixtime) OVER (\n      PARTITION BY run_id,\n      node_id\n      ORDER BY\n        unixtime\n    ) AS bucket_end\n  FROM\n    hosts\n)\nSELECT\n  CASE\n    WHEN ${time_meaning:sqlstring} = 'frame' THEN $__unixEpochGroup(latencies.unixtime/1000000, $bucket_interval, NULL)\n    ELSE $__unixEpochGroup(latencies.unixtime/1000000, $bucket_interval, NULL) + AVG(latency)\n  END as time,\n  AVG(latency) as latency,\n  CASE\n    WHEN MAX(coinc_upload_latency) = 0.0 THEN NULL\n    ELSE MAX(coinc_upload_latency)\n  END as coinc_upload_latency,\n  CASE\n    WHEN MAX(log_upload_latency) = 0.0 THEN NULL\n    ELSE MAX(log_upload_latency)\n  END as log_upload_latency,\n  bucketed_hosts.host,\n  latencies.node_id\nFROM\n  latencies\n  JOIN bucketed_hosts ON latencies.run_id = bucketed_hosts.run_id\n  AND latencies.node_id = bucketed_hosts.node_id\n  AND latencies.unixtime >= bucketed_hosts.bucket_start\n  AND (\n    bucketed_hosts.bucket_end is NULL\n    OR latencies.unixtime < bucketed_hosts.bucket_end\n  )\nWHERE\n  latencies.run_id in (${run_dir:sqlstring})\n  AND latencies.node_id in (${node_id:sqlstring})\n  AND $__unixEpochFilter(latencies.unixtime/1000000)\nGROUP BY\n  $__unixEpochGroup(latencies.unixtime/1000000, $bucket_interval, NULL),\n  latencies.node_id,\n  bucketed_hosts.host\nORDER BY\n  time,\n  latencies.node_id;"
    }
   ]
  },
  {
   "title": "state_vector",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH lagged_values AS (\r\n  SELECT\r\n    run_id,\r\n    node_id,\r\n    IFO,\r\n    unixtime/1000000 as time,\r\n    on_col,\r\n    off,\r\n    LAG(on_col) OVER (partition by run_id, node_id, ifo ORDER BY unixtime) AS prev_on,\r\n    LAG(off) OVER (partition by run_id, node_id, ifo ORDER BY unixtime) AS prev_off\r\n  FROM state_vector\r\n)\r\nSELECT\r\n  lagged_values.node_id,\r\n  lagged_values.IFO,\r\n  lagged_values.time,\r\n  CASE\r\n    WHEN (on_col - prev_on > 0) AND (off - prev_off > 0) THEN 0.5\r\n    WHEN (on_col - prev_on > 0) THEN 1\r\n    WHEN (off - prev_off > 0) THEN 0\r\n    ELSE -1\r\n  END AS value\r\nFROM lagged_values\r\nwhere run_id in (${run_dir:sqlstring}) AND node_id in (${node_id:sqlstring}) AND $__unixEpochFilter(time)\r\nORDER BY\r\n  time,\r\n  ifo,\r\n  node_id;\r\n"
    }
   ]
  },
  {
   "title": "Strain",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_id,\n  ifo,\n  unixtime/1000000 as time,\n  add_col,\n  drop_col\nFROM strain\nwhere run_id in (${run_dir:sqlstring}) AND node_id in (${node_id:sqlstring}) AND $__unixEpochFilter(strain.unixtime/1000000)\nORDER BY\n  time,\n  ifo,\n  node_id;"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time + 315964782 AS \"time\",\n  1 as live,\n  node_id,\n  CASE\n    WHEN segment_def_id = 0 THEN 'H1'\n    WHEN segment_def_id = 1 THEN 'L1'\n    WHEN segment_def_id = 2 THEN 'V1'\n  END as ifo\nFROM\n  segment\nWHERE\n  run_id in (${run_dir:sqlstring})\n  AND node_id in (${node_id:sqlstring})\n  AND $__unixEpochFilter(start_time + 315964782)\nUNION\nALL\nSELECT\n  end_time + 315964782 AS \"time\",\n  0 as live,\n  node_id,\n  CASE\n    WHEN segment_def_id = 0 THEN 'H1'\n    WHEN segment_def_id = 1 THEN 'L1'\n    WHEN segment_def_id = 2 THEN 'V1'\n  END as ifo\nFROM\n  segment\nWHERE\n  run_id in (${run_dir:sqlstring})\n  AND node_id in (${node_id:sqlstring})\n  AND $__unixEpochFilter(end_time + 315964782)\nORDER BY\n  time,\n  ifo,\n  node_id;"
    }
   ]
  },
  {
   "title": "Coinc events",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select\n  end_time + 315964782 as time,\n  mass,\n  mchirp,\n  snr,\n  1/combined_far as ifar\n  -- false_alarm_rate\nfrom\n  coinc_inspiral join runs on runs.run_id = coinc_inspiral.run_id\nwhere\n  coinc_inspiral.run_id in (${run_dir:sqlstring})\n  AND $__unixEpochFilter(end_time + 315964782);"
    }
   ]
  },
  {
   "title": "Zerolags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 262 },
   "collapsed": true,
   "panels": [
    {
     "title": "$run_dir",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "repeat": "run_dir",
     "targets": [
      {
       "rawSql": "SELECT\n  node_id,\n  $__unixEpochGroup(end_time+315964782, $bucket_interval, NULL) AS time,\n  AVG(cohsnr) as cohsnr,\n  AVG(cmbchisq) as cmbchisq,\n  AVG(fap) as fap,\n  AVG(far) as far,\n  AVG(far_2h) as far_2h,\n  AVG(far_1d) as far_1d,\n  AVG(far_1w) as far_1w,\n  AVG(mchirp) as mchirp,\n  AVG(nullsnr) as nullsnr\nFROM\n  postcoh\nWHERE run_id in (${run_dir:sqlstring})\nAND node_id in (${node_id:sqlstring})\nAND $__unixEpochFilter(end_time+315964782)\nGROUP BY\n  run_id,\n  node_id,\n  $__unixEpochGroup(end_time+315964782, $bucket_interval, NULL)\nORDER BY\n  time"
      }
     ]
    }
   ]
  },
  {
   "title": "Trigger frequencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 263 },
   "collapsed": true,
   "panels": [
    {
     "title": "$run_dir",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "repeat": "run_dir",
     "targets": [
      {
       "rawSql": "WITH time_series AS (\n  SELECT\n    generate_series(\n      min(\n        $__unixEpochGroup(latencies.unixtime, $bucket_interval)\n      ) :: int,\n      max(\n        $__unixEpochGroup(latencies.unixtime, $bucket_interval)\n      ) :: int,\n      extract(\n        epoch\n        from\n          interval ${bucket_interval:sqlstring}\n      )\n    ) AS time\n  FROM\n    latencies\n  WHERE\n    run_id in (${run_dir:sqlstring})\n    AND node_id in (${node_id:sqlstring})\n    AND $__unixEpochNanoFrom() - extract(\n      epoch\n      from\n        interval ${trigger_frequency:sqlstring}\n    ) < unixtime\n    AND unixtime < $__unixEpochNanoTo()\n),\nfrequencies AS (\n  SELECT\n    $__unixEpochGroup(unixtime, $bucket_interval) :: int AS time,\n    COUNT(*) OVER (\n      PARTITION BY node_id\n      ORDER BY\n        unixtime RANGE BETWEEN extract(\n          epoch\n          from\n            interval ${trigger_frequency:sqlstring}\n        ) PRECEDING\n        AND CURRENT ROW\n    ) AS frequency,\n    node_id\n  FROM\n    latencies\n  WHERE\n    run_id in (${run_dir:sqlstring})\n    AND node_id in (${node_id:sqlstring})\n    AND $__unixEpochNanoFrom() - extract(\n      epoch\n      from\n        interval ${trigger_frequency:sqlstring}\n    ) < unixtime\n    AND unixtime < $__unixEpochNanoTo()\n),\nnodes AS (\n  SELECT\n    DISTINCT node_id\n  FROM\n    latencies\n  WHERE\n    run_id in (${run_dir:sqlstring})\n    AND node_id in (${node_id:sqlstring})\n    AND $__unixEpochNanoFrom() - extract(\n      epoch\n      from\n        interval ${trigger_frequency:sqlstring}\n    ) < unixtime\n    AND unixtime < $__unixEpochNanoTo()\n)\nSELECT\n  time_series.time,\n  CASE\n    WHEN frequencies.frequency < 10 THEN NULL\n    ELSE COALESCE(frequencies.frequency, NULL)\n  END as frequency,\n  nodes.node_id\nFROM\n  time_series\n  CROSS JOIN nodes\n  LEFT JOIN frequencies ON time_series.time = frequencies.time :: int\n  AND nodes.node_id = frequencies.node_id\nORDER BY\n  time_series.time,\n  nodes.node_id;"
      }
     ]
    }
   ]
  }
 ]
}