#!/usr/bin/env bash
#SBATCH --job-name=crashcar
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mem=32g
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --array=0-1
#SBATCH -o logs/crashcar_%A_%a.out
#SBATCH -e logs/crashcar_%A_%a.err

set -euo pipefail

RUN_DIR=${RUN_DIR:?RUN_DIR required}
CRASH_ROOT=${CRASH_ROOT:?CRASH_ROOT required}
TOP_RUN_ROOT=${TOP_RUN_ROOT:?TOP_RUN_ROOT required}

cd "${RUN_DIR}"
mkdir -p logs monitor

export GST_DEBUG=${GST_DEBUG:-}
export X509_USER_PROXY=${X509_USER_PROXY:-}
export X509_USER_KEY=${X509_USER_KEY:-}
export X509_USER_CERT=${X509_USER_CERT:-}
export KRB5_KTNAME=${KRB5_KTNAME:-}
export PYTHONPATH=${PYTHONPATH:-}
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH:-}
export GST_PLUGIN_PATH=${GST_PLUGIN_PATH:-}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}

source /fred/oz016/gwdc_spiir_pipeline_codebase/scripts_n_things/build/bash_helper_functions.sh

{
  printf 'HOST=%s\n' "$(hostname)"
  printf 'UTC=%s\n' "$(date -u +%FT%TZ)"
  printf 'SLURM_JOB_ID=%s\n' "${SLURM_JOB_ID:-manual}"
  printf 'SLURM_ARRAY_TASK_ID=%s\n' "${SLURM_ARRAY_TASK_ID:-0}"
  env | grep -E '^(WGUO_O3A|CRASHCAR|BACKGROUND|FORMAL|DATA_|RUN_DIR|CRASH_ROOT|TOP_RUN_ROOT|SINGLE_)=' | sort
} > "logs/env_${SLURM_JOB_ID:-manual}_${SLURM_ARRAY_TASK_ID:-0}.env"

run_spiir_py3 \
	  -e SLURM_ARRAY_TASK_ID="${SLURM_ARRAY_TASK_ID:-0}" \
	  -e CRASH_ROOT="${CRASH_ROOT}" \
	  -e TOP_RUN_ROOT="${TOP_RUN_ROOT}" \
	  -e CRASHCAR_ENABLE="${CRASHCAR_ENABLE:-1}" \
	  -e WGUO_O3A_INJECTION_MODE="${WGUO_O3A_INJECTION_MODE:-none}" \
	  -e WGUO_O3A_INJECTION_FILE="${WGUO_O3A_INJECTION_FILE:-}" \
	  -e WGUO_O3A_START_GPS="${WGUO_O3A_START_GPS:?}" \
  -e WGUO_O3A_END_GPS="${WGUO_O3A_END_GPS:?}" \
  -e WGUO_O3A_DETRSP_MAP="${WGUO_O3A_DETRSP_MAP:-/fred/oz016/wguo/odds_ratio/O3a/chunk14/multi_det-BNS-LVK_inj/H1L1V1_1248134334_detrsp_map.xml}" \
  -e WGUO_O3A_FRAME_CACHE="${WGUO_O3A_FRAME_CACHE:-/fred/oz016/sunil/run_utils/frames_chache/frame_O3a.cache}" \
  -e WGUO_O3A_NONINJ_STATS_LOC="${WGUO_O3A_NONINJ_STATS_LOC:-/fred/oz016/wguo/odds_ratio/O3a/chunk2/multi_det-BNS}" \
  -e WGUO_O3A_BANK_DIR="${WGUO_O3A_BANK_DIR:-/fred/oz016/sunil/O3b_py3_banks}" \
  -e WGUO_O3A_START_BANK="${WGUO_O3A_START_BANK:-0}" \
  -e WGUO_O3A_BANKS_PER_GROUP="${WGUO_O3A_BANKS_PER_GROUP:-8}" \
  -e WGUO_O3A_SNAPSHOT_INTERVAL="${WGUO_O3A_SNAPSHOT_INTERVAL:-3600}" \
  -e WGUO_O3A_COLLECT_WALLTIME="${WGUO_O3A_COLLECT_WALLTIME:-10800,10800,10800}" \
  -e WGUO_O3A_GRACEDB_FAR_THRESH="${WGUO_O3A_GRACEDB_FAR_THRESH:-0}" \
  -e WGUO_O3A_FINALSINK_NEED_ONLINE_PERFORM="${WGUO_O3A_FINALSINK_NEED_ONLINE_PERFORM:-0}" \
  -e BACKGROUND_ACCUMULATION_SECONDS="${BACKGROUND_ACCUMULATION_SECONDS:-10800}" \
  -e FORMAL_BACKGROUND_ACCUMULATION_SECONDS="${FORMAL_BACKGROUND_ACCUMULATION_SECONDS:-10800}" \
  -e CRASHCAR_BACKGROUND_REQUIRED_SECONDS="${CRASHCAR_BACKGROUND_REQUIRED_SECONDS:-10800}" \
  -e BACKGROUND_UPDATE_TRIGGER_SECONDS="${BACKGROUND_UPDATE_TRIGGER_SECONDS:-3600}" \
  -e CRASHCAR_DOF="${CRASHCAR_DOF:?CRASHCAR_DOF is required}" \
  -e CRASHCAR_SNAPSHOT_INTERVAL_SECONDS="${CRASHCAR_SNAPSHOT_INTERVAL_SECONDS:-3600}" \
  -e CRASHCAR_LOG10_FAR_THRESHOLD="${CRASHCAR_LOG10_FAR_THRESHOLD:-90}" \
  -e CRASHCAR_PRESERVE_TABLE_SINGLE_FAR="${CRASHCAR_PRESERVE_TABLE_SINGLE_FAR:-0}" \
  -e CRASHCAR_FINALSINK_PRESERVE_TABLE_SINGLE_FAR="${CRASHCAR_FINALSINK_PRESERVE_TABLE_SINGLE_FAR:-1}" \
  -e CRASHCAR_TEMPLATE_SHAPE_MAP_FNAME="${CRASHCAR_TEMPLATE_SHAPE_MAP_FNAME:-}" \
  -e CRASHCAR_REQUIRE_TEMPLATE_SHAPE_MAP="${CRASHCAR_REQUIRE_TEMPLATE_SHAPE_MAP:-1}" \
  -e CRASHCAR_SEGMENT_LIVETIME_CSV="${CRASHCAR_SEGMENT_LIVETIME_CSV:-}" \
  -e CRASHCAR_EXPECTED_BUFFERS_PER_TIMESTAMP="${CRASHCAR_EXPECTED_BUFFERS_PER_TIMESTAMP:-}" \
  -e CRASHCAR_SUPPORT_DEBUG="${CRASHCAR_SUPPORT_DEBUG:-0}" \
	  -e CRASHCAR_SUPPORT_DEBUG_FNAME="${CRASHCAR_SUPPORT_DEBUG_FNAME:-}" \
	  -e CRASHCAR_CLUSTER_DEBUG="${CRASHCAR_CLUSTER_DEBUG:-0}" \
	  -e CRASHCAR_CLUSTER_DEBUG_FNAME="${CRASHCAR_CLUSTER_DEBUG_FNAME:-}" \
	  -e CRASHCAR_SNR_SERIES_LOG10_FAR_THRESHOLD="${CRASHCAR_SNR_SERIES_LOG10_FAR_THRESHOLD:-}" \
	  -e CRASHCAR_SNR_SERIES_OUTPUT_DIR="${CRASHCAR_SNR_SERIES_OUTPUT_DIR:-}" \
	  -e CRASHCAR_SNR_SERIES_WRITE_CSV="${CRASHCAR_SNR_SERIES_WRITE_CSV:-0}" \
	  -e CRASHCAR_SINGLE_SNR_SERIES_PRESELECT_ALL="${CRASHCAR_SINGLE_SNR_SERIES_PRESELECT_ALL:-0}" \
	  -e SINGLE_BACKGROUND_MODE="${SINGLE_BACKGROUND_MODE:-rolling}" \
	  -e CRASHCAR_SINGLE_BACKGROUND_MODE="${CRASHCAR_SINGLE_BACKGROUND_MODE:-${SINGLE_BACKGROUND_MODE:-rolling}}" \
	  -e SINGLE_FROZEN_BACKGROUND_JSON="${SINGLE_FROZEN_BACKGROUND_JSON:-}" \
	  -e CRASHCAR_FROZEN_SINGLE_SUPPORT_CSV="${CRASHCAR_FROZEN_SINGLE_SUPPORT_CSV:-}" \
		  -e CRASHCAR_CODE_VERSION="${CRASHCAR_CODE_VERSION:-spiir-crashcar}" \
  -e WGUO_O3A_SEGMENT_XML="${WGUO_O3A_SEGMENT_XML:-}" \
  -e SEGMENT_XML="${SEGMENT_XML:-}" \
  -e SINGLE_SEGMENT_XML="${SINGLE_SEGMENT_XML:-}" \
  wguo-single-det-py3 bash "${TOP_RUN_ROOT}/scripts/crashcar_pipeline.sh"

printf 'DONE %s\n' "$(date -u +%FT%TZ)" > "logs/done_${SLURM_JOB_ID:-manual}_${SLURM_ARRAY_TASK_ID:-0}.txt"
