#!/usr/bin/env bash
#SBATCH --ntasks=1
set -euo pipefail

RUN_DIR=${RUN_DIR:?RUN_DIR required}
CRASH_ROOT=${CRASH_ROOT:?CRASH_ROOT required}
TOP_RUN_ROOT=${TOP_RUN_ROOT:?TOP_RUN_ROOT required}
ROLE=${CRASHCAR_ROLE:?CRASHCAR_ROLE required}
WORKER=${SLURM_ARRAY_TASK_ID:-0}
WORKER_COUNT=${CRASHCAR_CURRENT_WORKER_COUNT:?worker count required}
BANKS_PER_WORKER=${WGUO_O3A_BANKS_PER_GROUP:?banks per worker required}
START_BANK=${WGUO_O3A_START_BANK:?start bank required}
JOBNO=$(printf '%03d' "${WORKER}")

ROSTER=
for bank in $(seq $((START_BANK + BANKS_PER_WORKER * WORKER)) $((START_BANK + BANKS_PER_WORKER * (WORKER + 1) - 1))); do
    [ -z "${ROSTER}" ] || ROSTER=${ROSTER},
    ROSTER=${ROSTER}${bank}
done
export CRASHCAR_WORKER_BANK_IDS_EXPECTED=${ROSTER}
export CRASHCAR_WORKER_COUNT=${WORKER_COUNT}

case "${ROLE}" in
    A)
        export CRASHCAR_SINGLE_BACKGROUND_JSON=${RUN_DIR}/${JOBNO}/single_background.json
        export WGUO_O3A_NONINJ_STATS_LOC=${RUN_DIR}
        ;;
    B)
        BACKGROUND_ROOT=${CRASHCAR_BACKGROUND_RUN_ROOT:?B background root required}
        [[ "${BACKGROUND_ROOT}" = /* ]] || { printf 'crashcar_sbatch: background root must be absolute\n' >&2; exit 2; }
        export CRASHCAR_SINGLE_BACKGROUND_JSON=${BACKGROUND_ROOT}/run/${JOBNO}/single_background.json
        export WGUO_O3A_NONINJ_STATS_LOC=${BACKGROUND_ROOT}/run
        ;;
    *) printf 'crashcar_sbatch: invalid role %s\n' "${ROLE}" >&2; exit 2 ;;
esac

cd "${RUN_DIR}"
mkdir -p logs monitor "${JOBNO}"
export GST_DEBUG=${GST_DEBUG:-}
export X509_USER_PROXY=${X509_USER_PROXY:-}
export X509_USER_KEY=${X509_USER_KEY:-}
export X509_USER_CERT=${X509_USER_CERT:-}
export KRB5_KTNAME=${KRB5_KTNAME:-}
source /fred/oz016/gwdc_spiir_pipeline_codebase/scripts_n_things/build/bash_helper_functions.sh

STATUS_FILE=${RUN_DIR}/logs/pipeline_exit_${SLURM_JOB_ID:-manual}_${WORKER}.status
rm -f -- "${STATUS_FILE}"
run_spiir_py3 \
  -e SLURM_ARRAY_TASK_ID="${WORKER}" \
  -e CRASHCAR_WORKER_ID="${WORKER}" \
  -e CRASH_ROOT="${CRASH_ROOT}" \
  -e TOP_RUN_ROOT="${TOP_RUN_ROOT}" \
  -e CRASHCAR_ROLE="${ROLE}" \
  -e CRASHCAR_BACKGROUND_RUN_ROOT="${CRASHCAR_BACKGROUND_RUN_ROOT:-}" \
  -e CRASHCAR_ENABLE="${CRASHCAR_ENABLE:-1}" \
  -e WGUO_O3A_INJECTION_FILE="${WGUO_O3A_INJECTION_FILE:-}" \
  -e WGUO_O3A_START_GPS="${WGUO_O3A_START_GPS:?}" \
  -e WGUO_O3A_END_GPS="${WGUO_O3A_END_GPS:?}" \
  -e WGUO_O3A_DETRSP_MAP="${WGUO_O3A_DETRSP_MAP:?}" \
  -e WGUO_O3A_FRAME_CACHE="${WGUO_O3A_FRAME_CACHE:?}" \
  -e WGUO_O3A_NONINJ_STATS_LOC="${WGUO_O3A_NONINJ_STATS_LOC:?}" \
  -e WGUO_O3A_BANK_DIR="${WGUO_O3A_BANK_DIR:?}" \
  -e WGUO_O3A_START_BANK="${START_BANK}" \
  -e WGUO_O3A_BANKS_PER_GROUP="${BANKS_PER_WORKER}" \
  -e WGUO_O3A_COLLECT_WALLTIME="${FINALSINK_FAPUPDATER_COLLECT_WALLTIME:?}" \
  -e FINALSINK_FAPUPDATER_COLLECT_WALLTIME="${FINALSINK_FAPUPDATER_COLLECT_WALLTIME:?}" \
  -e SNR_series_logFAR_threshold="${SNR_series_logFAR_threshold:?}" \
  -e BACKGROUND_ACCUMULATION_SECONDS="${BACKGROUND_ACCUMULATION_SECONDS:?}" \
  -e BACKGROUND_UPDATE_TRIGGER_SECONDS="${BACKGROUND_UPDATE_TRIGGER_SECONDS:?}" \
  -e COHFAR_ACCUMBACKGROUND_SNAPSHOT_INTERVAL_SECONDS="${COHFAR_ACCUMBACKGROUND_SNAPSHOT_INTERVAL_SECONDS:?}" \
  -e COHFAR_ASSIGNFAR_REFRESH_INTERVAL_SECONDS="${COHFAR_ASSIGNFAR_REFRESH_INTERVAL_SECONDS:?}" \
  -e FINALSINK_FAPUPDATER_INTERVAL_SECONDS="${FINALSINK_FAPUPDATER_INTERVAL_SECONDS:?}" \
  -e CRASHCAR_SNAPSHOT_INTERVAL_SECONDS="${CRASHCAR_SNAPSHOT_INTERVAL_SECONDS:?}" \
  -e CRASHCAR_LOG10_FAR_THRESHOLD="${CRASHCAR_LOG10_FAR_THRESHOLD:-90}" \
  -e TAIL_LOG_FAR="${TAIL_LOG_FAR:?}" \
  -e CRASHCAR_TEMPLATE_SHAPE_MAP_FNAME="${CRASHCAR_TEMPLATE_SHAPE_MAP_FNAME:?}" \
  -e CRASHCAR_SEGMENT_LIVETIME_JSON="${CRASHCAR_SEGMENT_LIVETIME_JSON:?}" \
  -e WGUO_O3A_SEGMENT_XML="${WGUO_O3A_SEGMENT_XML:?}" \
  -e CRASHCAR_WORKER_COUNT="${WORKER_COUNT}" \
  -e CRASHCAR_WORKER_BANK_IDS_EXPECTED="${ROSTER}" \
  -e CRASHCAR_SINGLE_BACKGROUND_JSON="${CRASHCAR_SINGLE_BACKGROUND_JSON}" \
  -e CRASHCAR_RUN_NAMESPACE_SHA256="${CRASHCAR_RUN_NAMESPACE_SHA256:?}" \
  -e CRASHCAR_SOURCE_MANIFEST_SHA256="${CRASHCAR_SOURCE_MANIFEST_SHA256:?}" \
  -e CRASHCAR_RUNTIME_MANIFEST_SHA256="${CRASHCAR_RUNTIME_MANIFEST_SHA256:?}" \
  -e CRASHCAR_CONFIG_SHA256="${CRASHCAR_CONFIG_SHA256:?}" \
  -e CRASHCAR_SEGMENT_XML_SHA256="${CRASHCAR_SEGMENT_XML_SHA256:?}" \
  -e CRASHCAR_SEGMENT_CANONICAL_SHA256="${CRASHCAR_SEGMENT_CANONICAL_SHA256:?}" \
  -e CRASHCAR_TEMPLATE_SHAPE_MAP_SHA256="${CRASHCAR_TEMPLATE_SHAPE_MAP_SHA256:?}" \
  -e CRASHCAR_CODE_VERSION="${CRASHCAR_CODE_VERSION:-spiir-crashcar-ab}" \
  -e CRASHCAR_PIPELINE_EXIT_STATUS_FILE="${STATUS_FILE}" \
  wguo-single-det-py3 bash "${TOP_RUN_ROOT}/scripts/crashcar_pipeline.sh"

[ -s "${STATUS_FILE}" ] || { printf 'crashcar_sbatch: pipeline status is missing\n' >&2; exit 125; }
IFS= read -r PIPELINE_RC < "${STATUS_FILE}"
rm -f -- "${STATUS_FILE}"
[[ "${PIPELINE_RC}" =~ ^(0|[1-9][0-9]{0,2})$ ]] || { printf 'crashcar_sbatch: invalid pipeline status\n' >&2; exit 125; }
exit "${PIPELINE_RC}"
